name: nativeplayer
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  get_it: ^7.3.0
  dartz: ^0.10.1
  video_player: ^2.2.14
  http: ^0.13.5
  html: ^0.15.4
  dio: ^5.1.0
  equatable: ^2.0.5
  intl: ^0.18.0
  pretty_dio_logger: ^1.3.1
  path_provider: ^2.1.1
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
